---
version: '2.3'

services:

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - ${PROLARR_PORT}:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped  

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ${PATH_DOWNLOADS}:/downloads
      - ${PATH_TV}:/tv
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped  

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${PATH_DOWNLOADS}:/downloads
      - ${PATH_MOVIES}:/movies
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - ./config/plex:/config
      - ${PATH_TV}:/tv
      - ${PATH_MOVIES}:/movies
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/transmission:/config
      - ${PATH_DOWNLOADS}:/downloads
      - ${PATH_DOWNLOADS}/watch:/watch
      - ${PATH_TV}:/tv
      - ${PATH_MOVIES}:/movies
    ports:
      - ${TRANSMISSION_PORT}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - ${OVERSEERR_PORT}:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ./config/overseerr:/config
    restart: unless-stopped  
  
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - ./config/homarr/configs:/app/data/configs
      - ./config/homarr/data:/data
      - ./config/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${HOMARR_PORT}:7575
    restart: unless-stopped  

  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
        - ${MEALIE_PORT}:9000 
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./config/mealie/data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - MAX_WORKERS=2
      - WEB_CONCURRENCY=10
      - BASE_URL=http://192.168.20.100:9925
    restart: unless-stopped

  twingate:
    image: twingate/connector:1
    container_name: ${TWINGATE_CONTAINER_NAME}
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LABEL_HOSTNAME=hostname
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    restart: unless-stopped

networks:
  media-center-network:
    external: true