---
version: '2.3'

services:

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - AUTO_UPDATE=true
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 8990:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv #optional
      - ./transmission/downloads/movies:/downloads #optional
    ports:
      - 8991:8989
    restart: unless-stopped  

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies #optional
      - ./transmission/downloads/movies:/downloads #optional
    ports:
      - 8992:7878
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./plex/config:/config
      - ./sonarr/tv:/tv
      - ./radarr/movies:/movies
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - HOST_WHITELIST=dnsname list #optional
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      - 8993:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./bazarr/config:/config
      - ./bazarr/movies:/movies #optional
      - ./bazarr/tv:/tv #optional
    ports:
      - 8994:6767
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      # - NZBGET_USER=nzbget #optional
      # - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - ./nzbget/config:/config
      - ./nzbget/downloads:/downloads #optional
    ports:
      - 8995:6789
    restart: unless-stopped  

networks:
  media-center-network:
    external: true    